// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omerhkbamrzgmjydtwmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tZXJoa2JhbXJ6Z21qeWR0d210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njk5MzUsImV4cCI6MjA2NTA0NTkzNX0.x7zqkY70cGonuAw8YxKp_nXMScosd9Kle6ZtELWG1ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);